ALTER TABLE sala
ALTER COLUMN sala TYPE VARCHAR(50);

ALTER TABLE curso
ALTER COLUMN nome TYPE VARCHAR(100);

ALTER TABLE disciplina
ALTER COLUMN nome TYPE VARCHAR(100);

ALTER TABLE professor
ALTER COLUMN nome TYPE VARCHAR(100);

ALTER TABLE disciplina
DROP COLUMN curso_id;

ALTER TABLE professor
DROP COLUMN disciplina_id;