CREATE TABLE curso(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nome VARCHAR(30) NOT NULL
);

CREATE TABLE disciplina(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nome VARCHAR(30) NOT NULL,
	curso_id INTEGER NOT NULL,
		FOREIGN KEY (curso_id) REFERENCES curso(id)
);

CREATE TABLE professor(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nome VARCHAR(30) NOT NULL,
	disciplina_id INTEGER NOT NULL,
		FOREIGN KEY (disciplina_id) REFERENCES disciplina(id)
);

CREATE TABLE dia(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	dia VARCHAR(30) NOT NULL
);

CREATE TABLE sala(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	sala VARCHAR(20) NOT NULL
);

CREATE TABLE aulas(
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	curso_id INTEGER NOT NULL,
		FOREIGN KEY (curso_id) REFERENCES curso(id),
	disciplina_id INTEGER NOT NULL,
		FOREIGN KEY (disciplina_id) REFERENCES disciplina(id),
	professor_id INTEGER NOT NULL,
		FOREIGN KEY (professor_id) REFERENCES professor(id),
	dia_id INTEGER NOT NULL,
		FOREIGN KEY (dia_id) REFERENCES dia(id),
	sala_id INTEGER NOT NULL,
		FOREIGN KEY (sala_id) REFERENCES sala(id),
	horarioInicio TIME NOT NULL,
	horarioFim TIME NOT NULL
);